export const DAY=86400000;
const STARTER_TRANSLATIONS={'안녕하세요':['Hallo; Guten Tag','Hello; Hi; Good afternoon'],'감사합니다':['Danke; Vielen Dank','Thank you; Thanks'],'네':['Ja','Yes'],'아니요':['Nein','No'],'물':['Wasser','Water'],'밥':['Reis; Mahlzeit','Rice; Meal'],'커피':['Kaffee','Coffee'],'학교':['Schule','School'],'집':['Haus; Zuhause','House; Home'],'친구':['Freund; Freundin','Friend'],'오늘':['Heute','Today'],'내일':['Morgen','Tomorrow']};
export function migrateWord(w){if(!w||typeof w!=='object')return w;const result={...w,srs:{...w.srs}},starter=STARTER_TRANSLATIONS[w.ko];if(w.needsEnglish){result.de=w.de||w.en||'';result.en='';}else{result.en=w.en??(starter&&w.de===starter[0]?starter[1]:'');result.de=w.de??(starter&&w.en===starter[1]?starter[0]:'');}result.needsEnglish=false;if(w.srs?.['ko-de']&&!result.srs['ko-en'])result.srs['ko-en']=w.srs['ko-de'];if(w.srs?.['de-ko']&&!result.srs['en-ko'])result.srs['en-ko']=w.srs['de-ko'];delete result.srs['ko-de'];delete result.srs['de-ko'];return result;}
export function translationAnswers(w){return [w.en,w.de].filter(s=>typeof s==='string'&&s.trim()).join('; ');}
export function translationDisplay(w){return [w.en&&'EN: '+w.en,w.de&&'DE: '+w.de].filter(Boolean).join(' · ');}
export function normalize(s){return String(s).normalize('NFKC').trim().toLocaleLowerCase('de').replace(/\s+/g,' ').replace(/[.!?。！？]+$/u,'');}
export function matches(answer,expected){return expected.split(';').some(v=>normalize(v)===normalize(answer));}
export function schedule(old={},correct,now=Date.now()){let streak=correct?(old.streak||0)+1:0;let interval=correct?(streak===1?1:streak===2?3:Math.min(180,Math.round((old.interval||3)*2))):0;return{streak,interval,due:now+(correct?interval*DAY:10*60000),reviews:(old.reviews||0)+1};}
export function csvEncode(words){const keys=['ko','en','de','roman','example','category','emoji'];return '\uFEFF'+[keys.join(','),...words.map(w=>keys.map(k=>'"'+String(w[k]||'').replaceAll('"','""')+'"').join(','))].join('\r\n');}
export function csvParse(text){text=text.replace(/^\uFEFF/,'');const delimiter=text.split(/\r?\n/)[0].includes(',')?',':';';let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(!quoted&&cell.length)throw Error('Ungültige CSV-Anführungszeichen.');else quoted=!quoted;}else if(c===delimiter&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Nicht geschlossenes CSV-Feld.');row.push(cell);if(row.some(Boolean))rows.push(row);const keys=rows.shift()||[];if(!keys.includes('ko')||(!keys.includes('en')&&!keys.includes('de')))throw Error('CSV braucht die Spalten ko und en.');return rows.map(r=>Object.fromEntries(keys.map((k,i)=>[k,r[i]||''])));}
export function validateWord(w){w=migrateWord(w);if(!w||typeof w!=='object'||typeof w.ko!=='string'||!w.ko.trim()||!translationAnswers(w).trim())throw Error('Jede Vokabel braucht Koreanisch (ko) und mindestens eine englische (en) oder deutsche (de) Bedeutung.');const out={};for(const [key,max] of Object.entries({ko:300,en:300,de:300,roman:300,example:1000,category:100,emoji:32})){if(w[key]!=null&&typeof w[key]!=='string')throw Error('Ungültiges Textfeld: '+key);out[key]=(w[key]||'').trim();if(out[key].length>max)throw Error('Textfeld zu lang: '+key);}if(out.emoji&&!/^(?:\p{Extended_Pictographic}|\p{Emoji_Presentation}|\p{Emoji_Modifier}|\u200d|\uFE0F|\uFE0E|[0-9#*]\uFE0F?\u20e3)+$/u.test(out.emoji))throw Error('Bitte im Emoji-Feld nur Emojis eingeben oder es leer lassen.');out.category||='Alltag';out.id=typeof w.id==='string'&&w.id.length<100?w.id:crypto.randomUUID();out.created=Number.isFinite(w.created)?w.created:Date.now();out.needsEnglish=Boolean(w.needsEnglish);out.srs={};for(const dir of ['ko-en','en-ko']){let s=w.srs?.[dir];if(s){if(!['due','interval','streak','reviews'].every(k=>Number.isFinite(s[k])&&s[k]>=0)||s.interval>180||s.streak>10000)throw Error('Ungültiger Lernstand.');out.srs[dir]={due:s.due,interval:s.interval,streak:s.streak,reviews:s.reviews};}}return out;}

