export const ROASTS=Object.freeze([
 'Das hätte meine Oma gewusst. Und die lernt Spanisch.',
 'Wie dumm bist du denn? Kleiner Spaß. Nächster Versuch.',
 'Dein Gehirn hat gerade Flugmodus aktiviert.',
 'Mutige Antwort. Leider komplett am Thema vorbei.',
 'So viel Selbstvertrauen bei so wenig Trefferquote.',
 'Du hast die richtige Antwort elegant umfahren.',
 'Das Wort hat dich angeschaut. Du hast zurückgeraten.',
 'Selbst die Autokorrektur würde sich davon distanzieren.',
 'Dein inneres Wörterbuch ist wohl noch originalverpackt.',
 'Knapp daneben ist auch eine stabile Lebensentscheidung.',
 'Die Antwort war kreativ. Wir suchen allerdings Koreanisch.',
 'Deine Oma hat gerade enttäuscht den Kopf geschüttelt.',
 'Der Wörterbuchverlag möchte nicht damit in Verbindung gebracht werden.',
 'Da hat dein Kopf wohl auf „Überspringen“ gedrückt.',
 'Die richtige Antwort stand kurz vor der Tür. Du hast nicht aufgemacht.',
 'Das war kein Tippfehler. Das war ein Abenteuer.',
 'Dein Gehirn lädt noch. Bitte nicht ausschalten.',
 'Du würfelst doch heimlich, oder?',
 'Das war sprachlich ungefähr ein Parkversuch auf dem Dach.',
 'Der Apfel hat gerade beschlossen, lieber eine Birne zu sein.',
 'Eine Antwort wie ein Bus: leider die falsche Linie.',
 'Immerhin hast du die Buchstaben gefunden.',
 'Koreanisch hat gerade einen Schritt von dir weg gemacht.',
 'Das Wort ist nicht schwer. Es hat nur gewonnen.',
 'Dein Gedächtnis hat eine sehr flexible Kündigungsfrist.',
 'Haus? Maus? Hauptsache irgendwas mit Buchstaben.',
 'Dein Wörterbuch ist offenbar ein Überraschungsei.',
 'Du und dieses Wort: aktuell eher Fernbeziehung.',
 'Dein Kopf hat die Antwort gesehen und trotzdem weggeschaut.',
 'So sieht es aus, wenn Bauchgefühl das Wörterbuch ersetzt.',
 'Die Grammatik war nicht mal dran und ist trotzdem beleidigt.',
 'Ein starkes Statement gegen die richtige Antwort.',
 'Das war nicht richtig. Aber sehr überzeugend falsch.',
 'Dein Hirn braucht offenbar erst einen Kaffee.',
 'Wissen ist Macht. Heute war kurz Stromausfall.',
 'Du hast gerade eine neue Sprache erfunden. Diese App kann sie nicht.',
 'Die Antwort war auf dem Weg. Dann kam ein Kreisverkehr.',
 'Ich glaube, die Vokabel gewinnt diese Runde durch K. o.',
 'Das hätte der Kühlschrank gewusst. Da hängt ein Lernzettel dran.',
 'Sehr schön geschrieben. Inhaltlich ein anderer Film.',
 'Du wolltest das Wort überraschen. Hat funktioniert.',
 'Dein Gedächtnis macht gerade Homeoffice ohne Internet.',
 'Das war die Antwort auf eine Frage, die niemand gestellt hat.',
 'Ein bisschen weniger Fantasie. Ein bisschen mehr Wörterbuch.',
 'Du lernst Koreanisch. Dein Kopf lernt offenbar Ausreden.',
 'Die richtige Antwort winkt dir vom anderen Ufer.',
 'Deine Trefferquote braucht heute einen Helm.',
 'So knapp daneben, dass ein Umzug nötig wäre.',
 'Dein Gehirn hat die Vokabel als Spam markiert.',
 'Das Wort stand auf deiner Liste. Dein Kopf stand daneben.',
 'Nicht mal das Konfetti wusste, wohin es fliegen soll.',
 'Die Vokabel hat gewonnen. Du darfst eine Revanche anmelden.',
 'Dein Kopf ist heute eher Deko als Datenbank.',
 'Da war mehr Hoffnung als Wissen im Spiel.',
 'Du hast alle Möglichkeiten genutzt. Außer der richtigen.',
 'Die Antwort hat sich verlaufen und möchte abgeholt werden.',
 'So viel Anlauf für so wenig Landung.',
 'Das war ein Überraschungsbesuch im falschen Wörterbuch.',
 'Dein Gedächtnis sagt: Noch nie gesehen. Die Statistik widerspricht.',
 'Oma hätte längst auf „Nächste Vokabel“ gedrückt.'
]);
let bag=[],last='';
export function wrongRoast(){if(!bag.length){bag=[...ROASTS];for(let i=bag.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]];}if(bag.at(-1)===last)[bag[0],bag[bag.length-1]]=[bag[bag.length-1],bag[0]];}return last=bag.pop();}
let confettiTimer;
export function clearConfetti(){clearTimeout(confettiTimer);document.querySelector('.confetti-layer')?.remove();}
export function celebrate(){clearConfetti();if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return;const layer=document.createElement('div');layer.className='confetti-layer';layer.setAttribute('aria-hidden','true');const colors=['#b9ee75','#78cfff','#ffc86b','#ee91bc','#c6a5ff'];for(let i=0;i<28;i++){const piece=document.createElement('i');piece.style.setProperty('--x',(4+Math.random()*92)+'%');piece.style.setProperty('--drift',(-65+Math.random()*130)+'px');piece.style.setProperty('--turn',(180+Math.random()*540)+'deg');piece.style.setProperty('--duration',(1100+Math.random()*500)+'ms');piece.style.setProperty('--delay',(Math.random()*160)+'ms');piece.style.backgroundColor=colors[i%colors.length];layer.append(piece);}document.body.append(layer);confettiTimer=setTimeout(()=>layer.remove(),1900);}
